DROP DATABASE IF EXISTS QuanLyBanHang;

CREATE DATABASE QuanLyBanHang;

USE QuanLyBanHang;

CREATE TABLE customer(
cID INT AUTO_INCREMENT,
cName VARCHAR(45),
cAge INT DEFAULT(18),
PRIMARY KEY(cID)
);

CREATE TABLE orders(
oID INT AUTO_INCREMENT,
cID INT NOT NULL,
oDate DATE NOT NULL,
oTotalPrice INT NOT NULL,
PRIMARY KEY(oID),
FOREIGN KEY(cID) REFERENCES customer(cID)
);

CREATE TABLE product(
pID INT AUTO_INCREMENT,
pName VARCHAR(45) NOT NULL,
pPrice INT NOT NULL,
PRIMARY KEY(pID)
);

CREATE TABLE order_detail(
oID INT NOT NULL,
pID INT NOT NULL,
odQTY INT DEFAULT(1),
PRIMARY KEY(oID,pID),
FOREIGN KEY(oID) REFERENCES orders(oID),
FOREIGN KEY(pID) REFERENCES product(pID)
);